### ISSUE TITLE
预览卡顿掉帧问题

### ISSUE THREAD

**Issue by ljmkimqx** [danjiang/DTCamera#2]
你好，我使用“Recording MP4(H264) with AVAssetWriter”栏进行预览时发现预览比较有明显的卡顿感，然后我查看项目，看到OpenGLPreviewView.swift文件的渲染是切换到主线程进行。

我看了下gpuimage库，GPUImageView它是在子线程里进行的渲染的。

有什么办法可以解决这个卡顿问题吗，我尝试过解决，比如OpenGLPreviewView.swift的渲染放在子线程里，但也是会卡顿。

我问过其他同事，让他们对比其他相机APP，他们也说这个项目的Demo看上去有掉帧的卡顿感。

**Comment by danjiang** [comment]
这个 Demo 的线程方面没有做特别处理，你可以看下 DTLiving 里面有参考 GPUImage 单独用一个 GCDQueue 来处理 GLContext 的交互。
