### ISSUE TITLE
关于OpenGLES处理CVPixelBuffer的纹理传递

### ISSUE THREAD

**Issue by DelogoTeam** [danjiang/DTCamera#3]
大神你好，我看了你的项目，写的超乎想象的好。但是我现在遇到了一个需求，是要求我对CVPixelBuffer转换的纹理进行多滤镜处理，然后再转换成CVPixelBuffer传出来。我用了你的EffectOpenGLFilter里的方法来实现，但是只能进行单滤镜处理，请问有什么方法或者思路可以进行多滤镜处理然后再转换成CVPixelBuffer吗？

**Comment by danjiang** [comment]
你看下 DTLiving 这个项目里面，VideoEffectProcessor 应该就是你想要的，DTCamera 只是走通了流程，视频滤镜没有做结构化的设计
